# Python for Sports Traders – Tennis Edition  
### From Zero to pandas Pro in One Notebook


Welcome!  
You need **no previous coding experience**. Follow along, run the cells (Shift + Enter), and tackle the practice tasks after each concept.

**Roadmap**

0. Meet Jupyter  
1. Python basics  
2. NumPy arrays  
3. pandas fundamentals  
4. Filtering & transformation  
5. Joining datasets (SQL-style)  
6. Grouping & aggregation  
7. Pivot tables (Excel vibe)  
8. Exporting results  
9. Batch processing  
10. Capstone mini‑project  


## 0. Meet Jupyter notebooks

Run the cell below—welcome to interactive coding!

In [1]:
print('Hello, sports world! 🎾')

Hello, tennis traders! 🎾


## 1. Python basics

### 1.1 Comments & printing

In [2]:

# A hashtag starts a comment that Python ignores.
print("Data-driven decisions win championships!")


Data-driven decisions win championships!


### 1.2 Basic arithmetic

In [3]:

# Division, multiplication, exponents
sets_won = 3
total_sets = 5
win_pct = sets_won / total_sets
print("Win percentage:", win_pct)


Win percentage: 0.6


> **Practice 1.1:** Calculate the break‑even probability for decimal odds **3.5** (hint: 1 / odds).

### 1.3 Variables & types

In [4]:

player = "Novak Djokovic"
odds = 1.75      
favorite = True  

print(type(player))
print(type(odds))
print(type(favorite))

<class 'str'>
<class 'float'>
<class 'bool'>


### 1.4 Lists – ordered collections

In [5]:

grand_slams = ["Australian Open", "Roland Garros", "Wimbledon", "US Open"]
print("Before append:", grand_slams)

# 🔑 Example: append adds an item to the end of a list
grand_slams.append("Davis Cup")
print("After append:", grand_slams)


Before append: ['Australian Open', 'Roland Garros', 'Wimbledon', 'US Open']
After append: ['Australian Open', 'Roland Garros', 'Wimbledon', 'US Open', 'Davis Cup']


> **Practice 1.2:** Append **'ATP Finals'** to `grand_slams` and print the updated list.

### 1.5 Dictionaries – key/value look‑ups

In [6]:

player_rank = {"Sinner": 1, "Alcaraz": 2}
print(player_rank)

# 🔑 Example: looping through a dict
for name, rank in player_rank.items():
    print(f"{name} is ranked #{rank}")


{'Sinner': 1, 'Alcaraz': 2}
Sinner is ranked #1
Alcaraz is ranked #2


> **Practice 1.3:** Add `'Sinner': 3` to `player_rank`, then write a loop that prints each player with their rank.

### 1.6 Control flow: if‑else and loops

In [7]:

profit = 40
if profit > 0:
    print("Great trade! 🎉")
else:
    print("Tough luck, review your edge.")


Great trade! 🎉


> **Practice 1.4:** Write an `if‐else` that prints *'Short odds'* if `odds < 2` else *'Long odds'*.

### 1.7 Defining functions

In [8]:

def implied_prob(decimal_odds):
    """Return probability implied by decimal odds."""
    return round(1 / decimal_odds, 3)

implied_prob(1.8)


0.556

> **Practice 1.5:** Write a function `net_profit(gross, commission_rate)` that subtracts the commission and returns the net figure.

## 2. NumPy – lightning‑fast arrays

In [9]:

import numpy as np

# Example array: set scores (player1, player2)
scores = np.array([[6,4],
                   [3,6],
                   [7,6]])
scores


array([[6, 4],
       [3, 6],
       [7, 6]])

In [10]:

# Row averages
scores.mean(axis=1)


array([5. , 4.5, 6.5])

In [11]:

# 🔑 Example: generate random match durations
durations = np.random.randint(90, 201, size=(4,4))
durations


array([[133,  95, 171, 138],
       [127, 107, 178, 108],
       [111, 118,  95, 190],
       [ 90, 111, 167, 120]], dtype=int32)

> **Practice 2.1:** Use NumPy to find the **longest** and **shortest** duration in `durations`.

## 3. pandas fundamentals – spreadsheets on rocket fuel

### 3.1 Loading tennis match data

In [12]:

import pandas as pd

matches_2024 = pd.read_csv("matches_2024.csv")
matches_2024.head()


match_id        date       tournament          player1           player2  \
0   2024001  2024-10-21        Wimbledon  Daniil Medvedev       Holger Rune   
1   2024002  2024-12-14  Australian Open  Daniil Medvedev     Andrey Rublev   
2   2024003  2024-09-07  Australian Open    Jannik Sinner  Alexander Zverev   
3   2024004  2024-01-08          US Open   Carlos Alcaraz     Jannik Sinner   
4   2024005  2024-03-18  Australian Open    Jannik Sinner  Alexander Zverev   

   p1_odds  p2_odds  p1_sets_won  p2_sets_won  
0     3.52     3.54            1            3  
1     2.09     3.77            4            3  
2     1.84     1.67            1            2  
3     2.39     1.38            4            2  
4     1.78     2.82            1            0

In [13]:
matches_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   match_id     10 non-null     int64  
 1   date         10 non-null     object 
 2   tournament   10 non-null     object 
 3   player1      10 non-null     object 
 4   player2      10 non-null     object 
 5   p1_odds      10 non-null     float64
 6   p2_odds      10 non-null     float64
 7   p1_sets_won  10 non-null     int64  
 8   p2_sets_won  10 non-null     int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 852.0+ bytes


> **Practice 3.1:** How many **unique tournaments** are in `matches_2024`? Hint: `nunique()`

### 3.2 Selecting columns & rows

In [14]:

# Column selection
matches_2024['player1'].head()

# Row selection by index
matches_2024.loc[0]


match_id               2024001
date                2024-10-21
tournament           Wimbledon
player1        Daniil Medvedev
player2            Holger Rune
p1_odds                   3.52
p2_odds                   3.54
p1_sets_won                  1
p2_sets_won                  3
Name: 0, dtype: object

### 3.3 Sorting

In [15]:

# 🔑 Example: sort by player1 odds (ascending)
sorted_odds = matches_2024.sort_values('p1_odds')
sorted_odds[['player1','p1_odds']].head()


player1  p1_odds
5  Alexander Zverev     1.51
4     Jannik Sinner     1.78
2     Jannik Sinner     1.84
1   Daniil Medvedev     2.09
3    Carlos Alcaraz     2.39

> **Practice 3.2:** Sort `matches_2024` by **`date` descending** and display the top 3 rows.

### 3.4 Creating new columns with `assign`

In [16]:

matches_2024 = matches_2024.assign(
    total_sets = matches_2024['p1_sets_won'] + matches_2024['p2_sets_won']
)
matches_2024[['match_id','total_sets']].head()


match_id  total_sets
0   2024001           4
1   2024002           7
2   2024003           3
3   2024004           6
4   2024005           1

In [17]:

# 🔑 Example: flag straight‑set wins
matches_2024['straight_sets'] = matches_2024['total_sets'] <= 3
matches_2024[['match_id','straight_sets']].head()


match_id  straight_sets
0   2024001          False
1   2024002          False
2   2024003           True
3   2024004          False
4   2024005           True

> **Practice 3.3:** Add a column **`went_to_five_sets`** that is `True` when `total_sets == 5`.

### 3.5 Handling missing data

In [18]:

# Inject a NaN for demo
matches_2024.loc[3,'p1_odds'] = np.nan
matches_2024.isna().sum()


match_id         0
date             0
tournament       0
player1          0
player2          0
p1_odds          1
p2_odds          0
p1_sets_won      0
p2_sets_won      0
total_sets       0
straight_sets    0
dtype: int64

In [19]:

# 🔑 Example: drop rows with any missing values
cleaned = matches_2024.dropna()
cleaned.shape


(9, 11)

> **Practice 3.4:** In `matches_2024`, fill missing `p1_odds` with the column **median** (`fillna`) and show the new missing‑value count.

### 3.6 Dates & times

In [20]:

matches_2024['date'] = pd.to_datetime(matches_2024['date'])
matches_2024['month'] = matches_2024['date'].dt.to_period('M')
matches_2024[['match_id','date','month']].head()


match_id       date    month
0   2024001 2024-10-21  2024-10
1   2024002 2024-12-14  2024-12
2   2024003 2024-09-07  2024-09
3   2024004 2024-01-08  2024-01
4   2024005 2024-03-18  2024-03

> **Practice 3.5:** Create a **`year`** column extracted from `date`.

### 3.7 Concatenating DataFrames

In [21]:

matches_all = pd.concat([
    matches_2024,
    pd.read_csv('matches_2025.csv')
], ignore_index=True)
matches_all.shape


(20, 12)

> **Practice 3.6:** Group `matches_all` by `year` (use the column you created) and count matches per year.

## 4. Filtering & transformation

In [22]:

# 🔑 Example: player1 odds < 1.8 AND straight‑set win
fast_win = matches_2024[
    (matches_2024['p1_odds'] < 1.8) &
    (matches_2024['straight_sets'])
]
fast_win.head()


match_id       date       tournament           player1           player2  \
4   2024005 2024-03-18  Australian Open     Jannik Sinner  Alexander Zverev   
5   2024006 2024-10-12        Wimbledon  Alexander Zverev       Holger Rune   

   p1_odds  p2_odds  p1_sets_won  p2_sets_won  total_sets  straight_sets  \
4     1.78     2.82            1            0           1           True   
5     1.51     2.59            1            1           2           True   

     month  
4  2024-03  
5  2024-10

> **Practice 4.1:** Filter `matches_2024` for matches where the **underdog** (higher odds) **won**. (Hint: compare odds vs. sets won)

In [23]:

# Example helper flag: did underdog win?
matches_2024['underdog_won'] = np.where(
    ((matches_2024['p1_odds'] > matches_2024['p2_odds']) & (matches_2024['p1_sets_won'] > matches_2024['p2_sets_won'])) |
    ((matches_2024['p2_odds'] > matches_2024['p1_odds']) & (matches_2024['p2_sets_won'] > matches_2024['p1_sets_won'])),
    True, False
)
matches_2024[['match_id','underdog_won']].head()


match_id  underdog_won
0   2024001          True
1   2024002         False
2   2024003         False
3   2024004         False
4   2024005         False

## 5. Joining trades to matches (think SQL JOIN)

In [24]:

trades = pd.read_csv('trades.csv')
joined = trades.merge(matches_all, on='match_id', how='left')
joined.head()


match_id   stake  profit                 date       tournament  \
0   2024005   81.53  -15.62  2024-03-18 00:00:00  Australian Open   
1   2024009  105.26   -0.03  2024-06-11 00:00:00        Wimbledon   
2   2024004   74.70  -53.87  2024-01-08 00:00:00          US Open   
3   2024001   73.98   -0.17  2024-10-21 00:00:00        Wimbledon   
4   2024007  130.90   35.82  2024-02-25 00:00:00          US Open   

           player1           player2  p1_odds  p2_odds  p1_sets_won  \
0    Jannik Sinner  Alexander Zverev     1.78     2.82            1   
1   Carlos Alcaraz  Alexander Zverev     3.59     2.24            4   
2   Carlos Alcaraz     Jannik Sinner      NaN     1.38            4   
3  Daniil Medvedev       Holger Rune     3.52     3.54            1   
4   Carlos Alcaraz   Daniil Medvedev     3.79     3.33            4   

   p2_sets_won  total_sets straight_sets    month  
0            0         1.0          True  2024-03  
1            2         6.0         False  2024-06  
2            2         6.0         False  2024-01  
3            3         4.0         False  2024-10  
4            4         8.0         False  2024-02

> **Practice 5.1:** How many trades in `joined` **did not** find a matching match row? (Hint: column `tournament` is NaN)

## 6. Grouping & aggregation

In [25]:

# 🔑 Example: aggregate P&L by tournament
summary = (
    joined.groupby('tournament')
          .agg(matches=('match_id','nunique'),
               total_staked=('stake','sum'),
               total_profit=('profit','sum'))
          .reset_index()
)
summary


tournament  matches  total_staked  total_profit
0  Australian Open        2        187.71        -57.94
1    Roland Garros        1        130.71        -86.96
2          US Open        3        256.50         -0.58
3        Wimbledon        4        375.80         -4.91

In [26]:

# Calculate ROI
summary['roi'] = round(summary['total_profit'] / summary['total_staked'], 3)
summary.sort_values('roi', ascending=False)


tournament  matches  total_staked  total_profit    roi
2          US Open        3        256.50         -0.58 -0.002
3        Wimbledon        4        375.80         -4.91 -0.013
0  Australian Open        2        187.71        -57.94 -0.309
1    Roland Garros        1        130.71        -86.96 -0.665

> **Practice 6.1:** Which tournament has the **highest average stake per match**? (Hint: add a column)

## 7. Pivot tables – quick multidimensional summaries

In [27]:

pivot = pd.pivot_table(
    joined,
    index='tournament',
    columns='player1',
    values='profit',
    aggfunc='sum',
    fill_value=0
)
pivot.head()


player1          Carlos Alcaraz  Daniil Medvedev  Jannik Sinner  \
tournament                                                        
Australian Open            0.00             0.00         -15.62   
Roland Garros              0.00             0.00           0.00   
US Open                  -18.05            17.47           0.00   
Wimbledon                -47.38            42.47           0.00   

player1          Novak Djokovic  Stefanos Tsitsipas  
tournament                                           
Australian Open            0.00              -42.32  
Roland Garros            -86.96                0.00  
US Open                    0.00                0.00  
Wimbledon                  0.00                0.00

> **Practice 7.1:** Create a pivot of **average `p1_odds`** by `tournament` vs. **`year`** (use the year column).

## 8. Exporting results

In [28]:

summary.to_csv('tournament_profit_summary.csv', index=False)

with pd.ExcelWriter('tournament_profit_summary.xlsx') as writer:
    summary.to_excel(writer, sheet_name='Summary', index=False)
    pivot.to_excel(writer, sheet_name='Pivot')
print('Files written ✓')


Files written ✓


> **Practice 8.1:** Save the `fast_win` DataFrame (from Section 4) to **CSV** named `fast_win.csv`.

## 9. Batch processing many files

In [29]:

from pathlib import Path

# 🔑 Example: read every matches_*.csv file
mega = pd.concat(
    [pd.read_csv(fp) for fp in Path('.').glob('matches_*.csv')],
    ignore_index=True
)
mega.shape


(20, 9)

> **Practice 9.1:** How many **distinct players** appear across **all** match files?

## 10. Capstone mini‑project – Monthly Tournament P&L dashboard


**Challenge steps**  
1. Merge every `matches_*.csv` with `trades.csv`.  
2. Subtract 5 % commission to create `net_profit`.  
3. Use `pd.pivot_table` to show **monthly** `net_profit` per **tournament**.  
4. Export the pivot to Excel and CSV.  
Bonus: highlight negative months with red background using `DataFrame.style`.  
